config/routes.rb
Diliver::Application.routes.draw do
  namespace :demo do
    get '/' => 'default#index'
    get '/team-identification' => 'default#team_identification'
    get '/transaction-analysis' => 'default#transaction_analysis'
    get '/screening' => 'default#screening'
    get '/qualification' => 'default#qualification'
    get '/preliminary-due-diligence' => 'default#preliminary_due_diligence'
    get '/initial-valuation' => 'default#initial_valuation'
    get '/confirmatory-due-diligence' => 'default#confirmatory_due_diligence'
    get '/valuation-preparation' => 'default#valuation_preparation'
    get '/final-valuation' => 'default#final_valuation'
  end

  resources :launch_surveys
  root to: 'default#index'
end

app/models/launch_survey.rb
class LaunchSurvey < ActiveRecord::Base
  attr_accessible :id, :mergers_acquisitions, :as_buyer, :as_seller, :as_intermediary, :personally_involved, 
  :specific_role, :title, :first_name, :last_name, :email, :created_at, :updated_at, :organization, :phone_number

  def full_name
  	"#{self.first_name} #{self.last_name}"
  end

end

app/controllers/launch_surveys_controller.rb
class LaunchSurveysController < ApplicationController
  # GET /launch_surveys
  # GET /launch_surveys.json
  def index
    # This will be replaced with login when we integrate devise
    if params["2mshdisl49i23mjnv2023jrincsd92jioecid"]
      @launch_surveys = LaunchSurvey.all

      respond_to do |format|
        format.html # index.html.erb
        #format.json { render json: @launch_surveys }
      end
    else
      redirect_to root_url, notice: 'You are not allowed to access this resource.'
    end
  end

  # GET /launch_surveys/1
  # GET /launch_surveys/1.json
  def show
    redirect_to root_url, notice: 'You are not allowed to access this resource.'
=begin
    @launch_survey = LaunchSurvey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @launch_survey }
    end
=end
  end

  # GET /launch_surveys/new
  # GET /launch_surveys/new.json
  def new
    redirect_to root_url, notice: 'You are not allowed to access this resource.'
=begin
    @launch_survey = LaunchSurvey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @launch_survey }
    end
=end
  end

  # GET /launch_surveys/1/edit
  def edit
    redirect_to root_url, notice: 'You are not allowed to access this resource.'
    #@launch_survey = LaunchSurvey.find(params[:id])
  end

  # POST /launch_surveys
  # POST /launch_surveys.json
  def create
    @launch_survey = LaunchSurvey.new(params[:launch_survey])

    respond_to do |format|
      if @launch_survey.save
        format.html { redirect_to root_url, notice: 'Survey completed successfully.' }
      else
        format.html { redirect_to root_url, notice: 'There was an issue with your survey. Please fill out the form and try again.' }
      end
    end
  end

  # PUT /launch_surveys/1
  # PUT /launch_surveys/1.json
  def update
    redirect_to root_url, notice: 'You are not allowed to access this resource.'
=begin
    @launch_survey = LaunchSurvey.find(params[:id])

    respond_to do |format|
      if @launch_survey.update_attributes(params[:launch_survey])
        format.html { redirect_to @launch_survey, notice: 'Launch survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @launch_survey.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # DELETE /launch_surveys/1
  # DELETE /launch_surveys/1.json
  def destroy
    redirect_to root_url, notice: 'You are not allowed to access this resource.'
=begin
    @launch_survey = LaunchSurvey.find(params[:id])
    @launch_survey.destroy

    respond_to do |format|
      format.html { redirect_to launch_surveys_url }
      format.json { head :no_content }
    end
=end
  end
end

app/helpers/launch_surveys_helper.rb
module LaunchSurveysHelper
end

app/views/launch_surveys/_form.html.erb
<%= form_for(@launch_survey) do |f| %>
  <% if @launch_survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@launch_survey.errors.count, "error") %> prohibited this launch_survey from being saved:</h2>

      <ul>
      <% @launch_survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/launch_surveys/edit.html.erb
<h1>Editing launch_survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @launch_survey %> |
<%= link_to 'Back', launch_surveys_path %>

app/views/launch_surveys/index.html.erb
<div class="middle_container center">
  <h2>Launch Surveys</h2>

  <br>

  <div class="launch_survey">
    <center>
      <table class="survey_listings">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Options</th>
          <th>Specific Role</th>
        </tr>

      <% @launch_surveys.each do |ls| %>
        <tr>
          <td><%= ls.full_name %></td>
          <td><%= ls.email %></td>
          <td><%= simple_format "<strong>Merger/Acquisition:</strong> #{ls.mergers_acquisitions}\n <strong>As Buyer:</strong> #{ls.as_buyer}, <strong>As Seller:</strong> #{ls.as_seller}, <strong>As Intermediary:</strong> #{ls.as_intermediary}\n <strong>Personally Involved:</strong> #{ls.personally_involved},\n<strong>Company:</strong> #{ls.organization}, <strong>Phone:</strong> #{ls.phone_number}" %></td>
          <td width="250px"><%= ls.specific_role %></td>
      <!--
          <td><%#= link_to 'Show', ls %></td>
          <td><%#= link_to 'Edit', edit_launch_survey_path(ls) %></td>
          <td><%#= link_to 'Destroy', ls, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      -->
        </tr>
      <% end %>
      </table>
    </center>
  </div>
</div>

<%#= link_to 'New Launch survey', new_launch_survey_path %>

app/views/launch_surveys/new.html.erb
<h1>New launch_survey</h1>

<%= render 'form' %>

<%= link_to 'Back', launch_surveys_path %>

app/views/launch_surveys/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_launch_survey_path(@launch_survey) %> |
<%= link_to 'Back', launch_surveys_path %>